version: '3.1'
services:
  astro:
    container_name: astro_predictions
    build:
      context: ./astroService
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - ./astroService:/app
    ports:
      - ${ASTRO_PORT_LOCAL}:${ASTRO_PORT}
    environment:
      - APP_MODE=${APP_MODE}
      - HOST=${ASTRO_HOST}
      - PORT=${ASTRO_PORT}
      - PORT_LOCAL=${ASTRO_PORT_LOCAL}




