version: '3.1'
services:
  astro:
    container_name: astro_predictions
    build:
      context: ./astroService
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
  auth:
    container_name: astroAuth
    build:
      context: ./authService
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    depends_on:
      - postgres
  messages:
    container_name: messagesSender
    build:
      context: ./messageSenderService
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
  postgres:
    image: postgres






