version: '3.9'
services:
  gateway:
    container_name: astroGateway
    build: ./apiGateway
    ports:
      - "8086:8085"
    depends_on:
      - astro
      - messages
      - auth
    networks:
      - astronet
  messages:
    container_name: messagesSenderService
    build: ./messageSenderService
    working_dir: /app
    ports:
      - "9090:9002"
    networks:
      - astronet
  astro:
    container_name: astrologyService
    build: ./astroService
    working_dir: /app
    ports:
      - "9091:9003"
    networks:
      - astronet
  auth:
    container_name: authAstroService
    build: ./authService
    working_dir: /app
    ports:
      - "9093:9004"
    depends_on:
      - postgres
    networks:
      - astronet
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=islam20011
      - POSTGRES_DB=usersDB
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - astronet
volumes:
  postgres_data:
networks:
  astronet:
      driver: bridge
