// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: astroService.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPredictionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendPredictionsRequest) Reset() {
	*x = SendPredictionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astroService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPredictionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPredictionsRequest) ProtoMessage() {}

func (x *SendPredictionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astroService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPredictionsRequest.ProtoReflect.Descriptor instead.
func (*SendPredictionsRequest) Descriptor() ([]byte, []int) {
	return file_astroService_proto_rawDescGZIP(), []int{0}
}

type SendPredictionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendPredictionsResponse) Reset() {
	*x = SendPredictionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astroService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPredictionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPredictionsResponse) ProtoMessage() {}

func (x *SendPredictionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astroService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPredictionsResponse.ProtoReflect.Descriptor instead.
func (*SendPredictionsResponse) Descriptor() ([]byte, []int) {
	return file_astroService_proto_rawDescGZIP(), []int{1}
}

type PredictionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sign string `protobuf:"bytes,1,opt,name=Sign,proto3" json:"Sign,omitempty"`
	Day  string `protobuf:"bytes,2,opt,name=Day,proto3" json:"Day,omitempty"`
}

func (x *PredictionRequest) Reset() {
	*x = PredictionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astroService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionRequest) ProtoMessage() {}

func (x *PredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astroService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionRequest.ProtoReflect.Descriptor instead.
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return file_astroService_proto_rawDescGZIP(), []int{2}
}

func (x *PredictionRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *PredictionRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type PredictionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateRange     string `protobuf:"bytes,1,opt,name=DateRange,proto3" json:"DateRange,omitempty"`
	CurrentDate   string `protobuf:"bytes,2,opt,name=CurrentDate,proto3" json:"CurrentDate,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Compatibility string `protobuf:"bytes,4,opt,name=Compatibility,proto3" json:"Compatibility,omitempty"`
	Mood          string `protobuf:"bytes,5,opt,name=Mood,proto3" json:"Mood,omitempty"`
	Color         string `protobuf:"bytes,6,opt,name=Color,proto3" json:"Color,omitempty"`
	LuckyNumber   string `protobuf:"bytes,7,opt,name=LuckyNumber,proto3" json:"LuckyNumber,omitempty"`
	LuckyTime     string `protobuf:"bytes,8,opt,name=LuckyTime,proto3" json:"LuckyTime,omitempty"`
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astroService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astroService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_astroService_proto_rawDescGZIP(), []int{3}
}

func (x *PredictionResponse) GetDateRange() string {
	if x != nil {
		return x.DateRange
	}
	return ""
}

func (x *PredictionResponse) GetCurrentDate() string {
	if x != nil {
		return x.CurrentDate
	}
	return ""
}

func (x *PredictionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PredictionResponse) GetCompatibility() string {
	if x != nil {
		return x.Compatibility
	}
	return ""
}

func (x *PredictionResponse) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *PredictionResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PredictionResponse) GetLuckyNumber() string {
	if x != nil {
		return x.LuckyNumber
	}
	return ""
}

func (x *PredictionResponse) GetLuckyTime() string {
	if x != nil {
		return x.LuckyTime
	}
	return ""
}

var File_astroService_proto protoreflect.FileDescriptor

var file_astroService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x73, 0x74, 0x72, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16,
	0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x39, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x61,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x61, 0x79, 0x22, 0x86, 0x02, 0x0a,
	0x12, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4d,
	0x6f, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6f, 0x6f, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x75, 0x63, 0x6b, 0x79, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4c, 0x75, 0x63, 0x6b,
	0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x75, 0x63, 0x6b, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x75, 0x63, 0x6b,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xf6, 0x01, 0x0a, 0x10, 0x41, 0x73, 0x74, 0x72, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x77, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x17, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_astroService_proto_rawDescOnce sync.Once
	file_astroService_proto_rawDescData = file_astroService_proto_rawDesc
)

func file_astroService_proto_rawDescGZIP() []byte {
	file_astroService_proto_rawDescOnce.Do(func() {
		file_astroService_proto_rawDescData = protoimpl.X.CompressGZIP(file_astroService_proto_rawDescData)
	})
	return file_astroService_proto_rawDescData
}

var file_astroService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_astroService_proto_goTypes = []interface{}{
	(*SendPredictionsRequest)(nil),  // 0: protobuf.SendPredictionsRequest
	(*SendPredictionsResponse)(nil), // 1: protobuf.SendPredictionsResponse
	(*PredictionRequest)(nil),       // 2: protobuf.PredictionRequest
	(*PredictionResponse)(nil),      // 3: protobuf.PredictionResponse
}
var file_astroService_proto_depIdxs = []int32{
	2, // 0: protobuf.AstrologyService.GetPrediction:input_type -> protobuf.PredictionRequest
	0, // 1: protobuf.AstrologyService.SendPredictions:input_type -> protobuf.SendPredictionsRequest
	3, // 2: protobuf.AstrologyService.GetPrediction:output_type -> protobuf.PredictionResponse
	1, // 3: protobuf.AstrologyService.SendPredictions:output_type -> protobuf.SendPredictionsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_astroService_proto_init() }
func file_astroService_proto_init() {
	if File_astroService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_astroService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPredictionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astroService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPredictionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astroService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astroService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_astroService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astroService_proto_goTypes,
		DependencyIndexes: file_astroService_proto_depIdxs,
		MessageInfos:      file_astroService_proto_msgTypes,
	}.Build()
	File_astroService_proto = out.File
	file_astroService_proto_rawDesc = nil
	file_astroService_proto_goTypes = nil
	file_astroService_proto_depIdxs = nil
}
