// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: messageService.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyPredictionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseStatus bool `protobuf:"varint,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
}

func (x *DailyPredictionsResponse) Reset() {
	*x = DailyPredictionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyPredictionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPredictionsResponse) ProtoMessage() {}

func (x *DailyPredictionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messageService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPredictionsResponse.ProtoReflect.Descriptor instead.
func (*DailyPredictionsResponse) Descriptor() ([]byte, []int) {
	return file_messageService_proto_rawDescGZIP(), []int{0}
}

func (x *DailyPredictionsResponse) GetResponseStatus() bool {
	if x != nil {
		return x.ResponseStatus
	}
	return false
}

type Receiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zodiac string `protobuf:"bytes,1,opt,name=Zodiac,proto3" json:"Zodiac,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_messageService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_messageService_proto_rawDescGZIP(), []int{1}
}

func (x *Receiver) GetZodiac() string {
	if x != nil {
		return x.Zodiac
	}
	return ""
}

func (x *Receiver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DailyPredictionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day       string      `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Receivers []*Receiver `protobuf:"bytes,2,rep,name=receivers,proto3" json:"receivers,omitempty"`
}

func (x *DailyPredictionsRequest) Reset() {
	*x = DailyPredictionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyPredictionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPredictionsRequest) ProtoMessage() {}

func (x *DailyPredictionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messageService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPredictionsRequest.ProtoReflect.Descriptor instead.
func (*DailyPredictionsRequest) Descriptor() ([]byte, []int) {
	return file_messageService_proto_rawDescGZIP(), []int{2}
}

func (x *DailyPredictionsRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DailyPredictionsRequest) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

var File_messageService_proto protoreflect.FileDescriptor

var file_messageService_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42,
	0x0a, 0x18, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x5a, 0x6f, 0x64, 0x69, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x5a, 0x6f, 0x64, 0x69, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5d, 0x0a, 0x17,
	0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x30, 0x0a, 0x09, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x32, 0x90, 0x01, 0x0a, 0x0e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e,
	0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x17, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messageService_proto_rawDescOnce sync.Once
	file_messageService_proto_rawDescData = file_messageService_proto_rawDesc
)

func file_messageService_proto_rawDescGZIP() []byte {
	file_messageService_proto_rawDescOnce.Do(func() {
		file_messageService_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageService_proto_rawDescData)
	})
	return file_messageService_proto_rawDescData
}

var file_messageService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messageService_proto_goTypes = []interface{}{
	(*DailyPredictionsResponse)(nil), // 0: protobuf.DailyPredictionsResponse
	(*Receiver)(nil),                 // 1: protobuf.Receiver
	(*DailyPredictionsRequest)(nil),  // 2: protobuf.DailyPredictionsRequest
}
var file_messageService_proto_depIdxs = []int32{
	1, // 0: protobuf.DailyPredictionsRequest.receivers:type_name -> protobuf.Receiver
	2, // 1: protobuf.MessageService.SendDailyPredictions:input_type -> protobuf.DailyPredictionsRequest
	0, // 2: protobuf.MessageService.SendDailyPredictions:output_type -> protobuf.DailyPredictionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messageService_proto_init() }
func file_messageService_proto_init() {
	if File_messageService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messageService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyPredictionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyPredictionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messageService_proto_goTypes,
		DependencyIndexes: file_messageService_proto_depIdxs,
		MessageInfos:      file_messageService_proto_msgTypes,
	}.Build()
	File_messageService_proto = out.File
	file_messageService_proto_rawDesc = nil
	file_messageService_proto_goTypes = nil
	file_messageService_proto_depIdxs = nil
}
